name = "UCIWWEIHR"
uuid = "176850df-a79a-485c-b76d-f2c16e00fafb"
authors = ["Christian O. Bernal Zelaya"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
